# vim:fileencoding=utf-8:filetype=toml
# Common configs
command_timeout = 1000
continuation_prompt = "[›](yellow) "
format = """
$status\
$sudo\
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_status\
$git_metrics\
$git_state\
$hg_branch\
$cmake\
$golang\
$helm\
$java\
$lua\
$nodejs\
$python\
$ruby\
$rust\
$terraform\
$aws\
$gcloud\
$kubernetes\
$env_var\
$cmd_duration\
${custom.proxy}\
$line_break\
$jobs\
$nix_shell\
${custom.venv}\
${custom.devpod}\
$character"""

[sudo]
disabled = false
format = "[$symbol]($style)"
style = "bold red"
symbol = "󰯄 "

[username]
format = "[$user]($style) "

[hostname]
format = "[@]($style) [$hostname]($style) "
style = "bright-black"

[directory]
format = "[$path]($style)[$read_only]($read_only_style)"
fish_style_pwd_dir_length = 1
truncation_length = 3
style = "bold blue"

[git_branch]
format = " [$symbol$branch]($style)"
style = "bright-black"
symbol = ""

[git_commit]
format = " [󰜘$hash](cyan)( [$tag](green))"
tag_disabled = false
tag_symbol = " "

[git_status]
format = "[$all_status$ahead_behind]($style)"
ahead = "[󰶼${count}](green)"
behind = "[󰶹${count}](green)"
diverged = "[󰶼${ahead_count}](green)󰶹${behind_count}"
conflicted = "󰄽󰄽"
deleted = ""
modified = ""
renamed = "󰄾󰄾"
staged = ""
stashed = ""
untracked = "?"

[git_metrics]
disabled = false
format = "( ([+$added]($added_style))([-$deleted]($deleted_style)))"

[git_state]
format = ' \([$state $progress_current/$progress_total]($style)\)'

[cmd_duration]
format = " [$duration]($style)"

[nix_shell]
format = "[$state $name]($style) "
style = "bright-black"

[status]
disabled = false
symbol = ""

[character]
error_symbol = "[λ](bold red)"
success_symbol = "[λ](bold purple)"
vicmd_symbol = "[ε](bold purple)"

# Custom
[custom.devpod]
command = "echo $DEVPOD_WORKSPACE_ID"
when = 'test "$DEVPOD_WORKSPACE_ID" != ""'
format = "[$symbol$output]($style) "
style = "bright-black"
symbol = " "

[custom.proxy]
command = 'echo $HTTPS_PROXY | sed "s/http\:\/\///gi;s/\/$//gi"'
when = 'test "$HTTPS_PROXY" != ""'
format = " [$symbol$output]($style)"
style = "#ffaf87"
symbol = "󰒄 "

[custom.venv]
command = 'basename "$VIRTUAL_ENV"'
when = 'test "$VIRTUAL_ENV" != ""'
format = "[$output]($style) "
style = "bright-black"

# Platforms support
[aws]
format = ' [$symbol( $profile)( \($region\))( \[$duration\])]($style)'
style = "bold #ff9900"
symbol = "󰸏"

[docker_context]
format = " [$symbol$context]($style)"
style = "bold #0db7ed"
symbol = "󰡨 "

[kubernetes]
disabled = false
format = " [$symbol$context]($style)[@](bright-black)[$namespace]($style)"
style = "bold #326ce5"
symbol = "󱃾 "

[gcloud]
format = " [$symbol( $project[@](bright-black)$region)]($style)"
symbol = "󱇶"
style = "bold #4285f4"

# Languages support
[cmake]
format = " [$symbol($version)]($style)"
style = "bold #e25241"

[golang]
format = " [$symbol$version]($style)"
style = "bold #29beb0"
symbol = " "
version_format = "$raw"

[java]
format = " [$symbol$version]($style)"
style = "bold #ffa518"
symbol = " "
version_format = "$raw"

[lua]
format = " [$symbol$version]($style)"
style = "bold #29beb0"
symbol = " "
version_format = "$raw"

[nodejs]
format = " [$symbol$version]($style)"
style = "bold #3c873a"
symbol = " "
version_format = "$raw"

[python]
format = " [$symbol$version]($style)"
style = "bold #ffd43b"
symbol = " "
version_format = "$raw"

[ruby]
format = " [$symbol$version]($style)"
style = "bold #d51f06"
symbol = " "
version_format = "$raw"

[rust]
format = " [$symbol$version]($style)"
style = "bold #b7410e"
symbol = "󱘗 "
version_format = "$raw"

[terraform]
format = " [$symbol$version]($style)"
style = "bold #844fba"
symbol = "󱁢 "
version_format = "$raw"
