[flags]
basic = true
battery = false
default_widget_type = "proc"
disable_click = true
group_processes = false
tree = true

[processes]
columns = ["pid", "mem%", "cpu%", "name", "state", "user", "time"]

[layout]
[[row]]
  [[row.child]]
  type="cpu"
[[row]]
  [[row.child]]
    type="mem"
  [[row.child]]
    type="proc"
