---@class vim.lsp.Config
return {
  cmd = { "harper-ls", "--stdio" },
  filetypes = {
    "c",
    "cmake",
    "context",
    "cpp",
    "cs",
    "dart",
    "gitcommit",
    "go",
    "haskell",
    "html",
    "java",
    "javascript",
    "lua",
    "mail",
    "markdown",
    "nix",
    "org",
    "pandoc",
    "php",
    "python",
    "quarto",
    "rmd",
    "rnoweb",
    "rst",
    "ruby",
    "rust",
    "swift",
    "text",
    "toml",
    "typescript",
    "typescriptreact",
    "typst",
  },
  settings = {
    ["harper-ls"] = {
      userDictPath = vim.fn.expand("~/.config/harper-ls/dictionary.txt"),
      fileDictPath = vim.fn.expand("~/.config/harper-ls/file-dictionaries"),
      dialect = "British",
    },
  },
}
