#!/usr/bin/env bash

PLUGIN_DIR="$CONFIG_DIR/plugins"

sketchybar -m --bar \
	position=top \
	height=40 \
	color=0xff282a36 \
	display=main \
	topmost=off

default=(
	padding_left=5
	padding_right=5

	icon.font="SamsungSans Nerd Font:Regular:16.0"
	icon.color=0xffeff0eb
	icon.padding_left=8
	icon.padding_right=8

	label.color=0xffeff0eb
	label.font="SamsungSans Nerd Font:Regular:16.0"
	label.padding_left=0
	label.padding_right=8
)
sketchybar --default "${default[@]}"

sketchybar --add event aerospace_workspace_change

WORKSPACE_LABELS=(
	[1]=" " [2]=" " [3]=" " [4]=" " [5]=" "
	[6]=" " [7]=" " [8]=" " [9]=" " [0]=""
)
for sid in $(aerospace list-workspaces --all); do
	sketchybar \
		--add item space."$sid" left \
		--subscribe space."$sid" aerospace_workspace_change \
		--set space."$sid" \
		background.color=0xff57c7ff \
		background.corner_radius=0 \
		icon="$sid" \
		label="${WORKSPACE_LABELS[$sid]}" \
		script="$CONFIG_DIR/plugins/aerospace.sh $sid" \
		click_script="aerospace workspace $sid"
done

sketchybar \
	--add item clock right \
	--set clock update_freq=10 icon= script="$PLUGIN_DIR/clock.sh" \
	--add item volume right \
	--set volume script="$PLUGIN_DIR/volume.sh" \
	--subscribe volume volume_change \
	--add item battery right \
	--set battery update_freq=120 script="$PLUGIN_DIR/battery.sh" \
	--subscribe battery system_woke power_source_change

sketchybar --update
