#!/usr/bin/env bash

PLUGIN_DIR="$CONFIG_DIR/plugins"

COLOR_BLACK=0xff282a36
COLOR_BLUE=0xff57c7ff
COLOR_WHITE=0xffeff0eb

sketchybar -m --bar \
	position=top \
	height=40 \
	color="$COLOR_BLACK" \
	display=main \
	topmost=off

default=(
	padding_left=5
	padding_right=5

	icon.font='SamsungSans Nerd Font:Regular:17.0'
	icon.color="$COLOR_WHITE"
	icon.padding_left=8
	icon.padding_right=0

	label.font='SamsungSans Nerd Font:Regular:17.0'
	label.color="$COLOR_WHITE"
	label.padding_left=8
	label.padding_right=8
)
sketchybar --default "${default[@]}"

sketchybar --add event aerospace_workspace_change

WORKSPACE_LABELS=(
	[1]=" ₁" [2]=" ₂" [3]=" ₃" [4]=" ₄" [5]=" ₅"
	[6]=" ₆" [7]=" ₇" [8]=" ₈" [9]=" ₉" [0]=""
)
for sid in $(/run/current-system/sw/bin/aerospace list-workspaces --all); do
	sketchybar \
		--add item space."$sid" left \
		--subscribe space."$sid" aerospace_workspace_change \
		--set space."$sid" \
		background.color="$COLOR_BLUE" \
		background.corner_radius=0 \
		background.height=40 \
		icon="$sid" \
		icon.drawing=off \
		label="${WORKSPACE_LABELS[$sid]}" \
		script="$CONFIG_DIR/plugins/aerospace.sh $sid" \
		click_script="/run/current-system/sw/bin/aerospace workspace $sid"
done

sketchybar \
	--add item clock right \
	--set clock update_freq=10 icon="" script="$PLUGIN_DIR/clock.sh"

sketchybar \
	--add item volume right \
	--set volume script="$PLUGIN_DIR/volume.sh" \
	--subscribe volume volume_change

sketchybar \
	--add item battery right \
	--set battery update_freq=120 script="$PLUGIN_DIR/battery.sh" \
	--subscribe battery system_woke power_source_change

sketchybar \
	--add item mpd right \
	--set mpd script="$PLUGIN_DIR/mpd.sh" \
	--set mpd click_script="mpc toggle" \
	--add event mpd_idle \
	--subscribe mpd mpd_idle

sketchybar --update
