font = Operator Mono Lig Book:size=12
shell = /usr/bin/bash -l

[scrollback]
lines = 10000

[cursor]
style=block
blink=yes

[mouse]
hide-when-typing=yes

[colors]
alpha=1.0
foreground  = eff0eb
background  = 2a2a38

# Black
regular0    = 282a36
bright0     = 686868

# Red
regular1    = ff5c57
bright1     = ff5c57

# Green
regular2    = 5af78e
bright2     = 5af78e

# Yellow
regular3    = f3f99d
bright3     = f3f99d

# Blue
regular4    = 57c7ff
bright4     = 57c7ff

# Magenta
regular5    = ff6ac1
bright5     = ff6ac1

# Cyan
regular6    = 9aedfe
bright6     = 9aedfe

# White
regular7    = eff0eb
bright7     = eff0eb
