[settings]
experimental = true
lockfile = true

[tools]
# Languages go first
clang = "22.1.0"
go = "1.26.1"
java = "openjdk-21.0.2"
lua = "5.5.0"
luajit = "2.1.1744318430"
node = "22.17.1"
python = "3.12.12"
ruby = "4.0.1"
rust = "1.94.0"
terraform = "1.14.6"

# Then tools
awscli = { version = "2.34.4", symlink_bins = "true" }
cmake = "4.2.3"
firebase = "15.8.0"
gcloud = "559.0.0"
gh = "2.87.3"
helm = "4.1.1"
make = "4.4.1"
ninja = "1.13.2"
opencode = "1.2.20"
pre-commit = "4.5.1"
tree-sitter = "0.26.6"
