#!/usr/bin/env bash
set -o errexit
set -o pipefail
set -o nounset

readonly GREEN='\033[0;32m'
readonly ORANGE='\033[0;33m'
readonly BOLD='\033[1m'
readonly NORMAL='\033[0m'

PATH="/usr/local/bin:/usr/local/sbin:$(getconf PATH)"
ZSH="$HOME/.oh-my-zsh"
steps_count=0

function format_date_time() {
  date +"%Y-%m-%d %H:%M:%S %z"
}

function print_step() {
  steps_count=$((steps_count+1))
  local message=$1
  printf "\n${GREEN}${BOLD}❯ ${steps_count}. ${message}${NORMAL}\n"
}

function print_timestamp() {
  local prefix=$1
  printf "\n${ORANGE}$prefix at $(format_date_time)${NORMAL}\n"
}

function push_notification() {
  local timestamp="$1 at: $(format_date_time)"
  local title="Scheduled auto update"
  local sender="com.apple.Automator"

  terminal-notifier \
    -message "$timestamp" \
    -title "$title" \
    -sender $sender
}

function update_homebrew() {
  print_step "Update Homebrew"
  brew update --verbose
  brew upgrade --verbose
  brew upgrade --cask --verbose
  brew cleanup
  brew bundle dump --global --force
  chezmoi add ~/.Brewfile
}

function update_other_resources() {
  print_step "Update other resources"
  cd "$ZSH" && sh "$ZSH/tools/upgrade.sh" --verbose
  nvim --headless +PlugUpgrade +PlugUpdate +qa
  vim +PlugUpgrade +PlugUpdate +qa
}

function main() {
  print_timestamp "Auto update started"
  push_notification "Started"

  update_homebrew && update_other_resources

  print_timestamp "Backup finished"
  push_notification "Finished"
}

main
