live_config_reload = true
working_directory = "None"

[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = "0x686868"
blue = "0x57c7ff"
cyan = "0x9aedfe"
green = "0x5af78e"
magenta = "0xff6ac1"
red = "0xff5c57"
white = "0xeff0eb"
yellow = "0xf3f99d"

[colors.normal]
black = "0x282a36"
blue = "0x57c7ff"
cyan = "0x9aedfe"
green = "0x5af78e"
magenta = "0xff6ac1"
red = "0xff5c57"
white = "0xeff0eb"
yellow = "0xf3f99d"

[colors.primary]
background = "0x282a36"
foreground = "0xeff0eb"

[cursor]
style = "Block"
unfocused_hollow = true

[debug]
log_level = "Warn"
persistent_logging = false
print_events = false
render_timer = false

[env]
TERM = "xterm-256color"

[font]
builtin_box_drawing = true
size = 9.0

[font.bold]
family = "OperatorMonoSSm Nerd Font"
style = "Regular"

[font.bold_italic]
family = "OperatorMonoSSm Nerd Font"
style = "Italic"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "OperatorMonoSSm Nerd Font"
style = "Light Italic"

[font.normal]
family = "OperatorMonoSSm Nerd Font"
style = "Light"

[font.offset]
x = 0
y = 0

[mouse]
hide_when_typing = true

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

#[shell]
#args = ["-flp", "ethanify"]
#program = "/usr/bin/login"

[window]
decorations = "none"
dynamic_padding = false
dynamic_title = true
option_as_alt = "OnlyLeft"
startup_mode = "Maximized"

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 0
y = 0
