[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = "0x686868"
blue = "0x57c7ff"
cyan = "0x9aedfe"
green = "0x5af78e"
magenta = "0xff6ac1"
red = "0xff5c57"
white = "0xeff0eb"
yellow = "0xf3f99d"

[colors.normal]
black = "0x282a36"
blue = "0x57c7ff"
cyan = "0x9aedfe"
green = "0x5af78e"
magenta = "0xff6ac1"
red = "0xff5c57"
white = "0xeff0eb"
yellow = "0xf3f99d"

[colors.primary]
background = "0x282a36"
foreground = "0xeff0eb"

[cursor]
style = "Block"
unfocused_hollow = true

[debug]
log_level = "Warn"
persistent_logging = false
print_events = false
render_timer = false

[env]
TERM = "xterm-256color" # set to `alacritty` for latest TERM supports

[font]
builtin_box_drawing = true
size = 18.0
offset = { x = 0, y = 0 }
glyph_offset = { x = 0, y = 0 }
normal = { family = "OperatorMonoSSm Nerd Font", style = "Light" }
italic = { family = "OperatorMonoSSm Nerd Font", style = "Light Italic" }
bold = { family = "OperatorMonoSSm Nerd Font", style = "Regular" }
bold_italic = { family = "OperatorMonoSSm Nerd Font", style = "Italic" }

[mouse]
hide_when_typing = false
bindings = [
  { mouse = "Middle", action = "PasteSelection" }
]

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

# [terminal]
# shell = { program = "/opt/homebrew/bin/zsh", args = ["--login"] }

[window]
decorations = "none"
dynamic_padding = false
dynamic_title = true
option_as_alt = "OnlyLeft"
startup_mode = "Maximized"
dimensions = { columns = 0, lines = 0 }
padding = { x = 0, y = 0 }

[general]
live_config_reload = true
working_directory = "None"
