lowercaseKeywords: false
connections:
  - alias: local
    driver: postgresql
    proto: tcp
    user: postgres
    passwd: postgres
    host: localhost
    port: 5432
    dbName: postgres
    params:
      sslmode: disable
